name: build-deploy-pr
on:
  pull_request:
  repository_dispath:
    types: [release-build, force-rebuild]
jobs:
  deploy-images:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      username: ${{ github.event.organization.login || github.repository_owner }}
      repository: geocoder
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create latest tag variable
        run: |
          container="${{ env.registry }}/${{ env.username}}/${{ env.repository }}:latest"
          echo "container=${container}" >> $GITHUB_ENV
      - name: create pull request tag variable based on name of associated branch
        if: github.event_name == 'pull_request'
        run: |
          versioned="${{ env.registry }}/${{ env.username}}/${{ env.repository }}:${GITHUB_HEAD_REF}"
          echo "versioned=${versioned}" >> $GITHUB_ENV
      - name: build container
        run: |
          docker build -t ${{ env.container }} .
      - name: test run container
        run: |
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv 0.6
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv all
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ env.username }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy pull request container
        run: |
          docker tag ${{ env.container }} ${{ env.versioned }}
          docker push ${{ env.versioned }}
