name: build-deploy-release
on:
  release:
    types: [published]
  repository_dispatch:
    types: [release-build, force-rebuild]

jobs:
  deploy-images:
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      username: ${{ github.event.organization.login || github.repository_owner }}
      repository: build_degauss_db

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to read tags
      - name: create latest tag variable
        run: |
          container="${{ env.registry }}/${{ env.username }}/${{ env.repository }}:latest"
          echo "container=${container}" >> $GITHUB_ENV
      - name: create release tag variable
        if: github.event_name == 'release'
        run: |
          versioned="${{ env.registry }}/${{ env.username }}/${{ env.repository }}:${GITHUB_REF##*/}"
          echo "versioned=${versioned}" >> $GITHUB_ENV
      - name: Build image
        run: |
          docker build -t "${{ env.versioned }}" -t "${{ env.latest }}" .

      - name: Test image
        run: |
          docker run --rm "${{ env.versioned }}" sqlite3 --version
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images
        run: |
          docker tag  ${{ env.versioned }} ${{ env.versioned }}
          docker push ${{ env.versioned }}
          docker push ${{ env.latest }}