name: build-deploy-release
on:
  release:
    types: [published]
  repository_dispatch:
    types: [release-build, force-rebuild]
jobs:
  deploy-images:
    environment: geocoder_release_build
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      username: ${{ github.event.organization.login || github.repository_owner }}
      repository: geocoder
      GEOCODER_S3_LOCATION: ${{ vars.GEOCODER_S3_LOCATION }}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: create latest tag variable
        run: |
          container="${{ env.registry }}/${{ env.username }}/${{ env.repository }}:latest"
          echo "container=${container}" >> $GITHUB_ENV
      - name: create release tag variable
        if: github.event_name == 'release'
        run: |
          versioned="${{ env.registry }}/${{ env.username }}/${{ env.repository }}:${GITHUB_REF##*/}"
          echo "versioned=${versioned}" >> $GITHUB_ENV
      - name: build container
        run: |
          docker build --build-arg GEOCODER_S3_LOCATION="${GEOCODER_S3_LOCATION}" -t ${{ env.container }} .
      - name: test container
        run: |
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv 0.6
          docker run --rm -v "${PWD}/test":/tmp ${{ env.container }} my_address_file.csv all
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ env.username }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: deploy release (and latest) container
        run: |
          docker tag ${{ env.container }} ${{ env.versioned }}
          docker push ${{ env.versioned }}
          docker push ${{ env.container }}
