name: Build geocoder.db

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build-geocoder-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfiles/Dockerfile-build-db -t geocoder-db .

      - name: Run Docker container
        run: |
          docker run --name geocoder-db-container geocoder-db

      - name: Copy geocoder.db out of container
        run: |
          docker cp geocoder-db-container:/workspace/geocoder.db ./geocoder.db

      - name: Archive geocoder.db as artifact
        uses: actions/upload-artifact@v4
        with:
          name: geocoder.db
          path: ./geocoder.db

      # Optional: If you want to push to S3, uncomment and add AWS credentials as secrets
      # - name: Upload geocoder.db to S3
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "us-east-1"
      #   run: |
      #     aws s3 cp ./geocoder.db s3://choa-geocoding/census/geocoder.db